import { useGetAutoGeneratedVchNoQuery } from "../service/transactionsApi";
import useSelectedOrg from "./useSelectedOrg";

const useGetAutoGeneratedVchNo = (voucherName, voucherDate=new Date()) => {
    const { '_id': orgId } = useSelectedOrg();
    const { data } = useGetAutoGeneratedVchNoQuery({
        orgId, voucherName, 
        voucherDate:voucherDate.toDateString(),
    }, {skip: !orgId || !voucherName});
    if (voucherName) return data?.voucherNumber;
};

export default useGetAutoGeneratedVchNo;
