
export const styles = {
    page: {
      padding: 30,
      backgroundColor: '#ffffff',
      fontFamily: 'Roboto',
      fontWeight:'normal',
    },
    header: {
      padding:10,
      borderBottom:'1px solid #eee',
      textAlign:'left',
      padding: '20px 5px 35px'
    },
    logo: {
      height: 60,
    },
    documentNameContainer:{
      padding:'35px 0 50px', 
      textAlign:'center'
    },
    documentName:{
      fontSize: 16,
      fontFamily: 'Roboto',
      fontWeight: 'normal',
      textDecoration:'underline',
      textDecorationColor: '#00000040',
      // borderBottom: '1px solid #eee',
    },
    companyName: {
      fontSize: 18,
      fontFamily: 'Roboto',
      fontWeight: 'bold',
    },
    address: {
      fontSize: 10,
      lineHeight: 1.5,
      fontFamily:'Roboto',
    },
    receiptTransactionDetails:{
      display:'flex', 
      flexDirection:'row', 
      justifyContent:'space-between',
      flexWrap:'nowrap',
    },
    receiptDetailsColLeft:{
      width:'70%', 
      flexBasis:'70%',
    },
    receiptDetailsColRight:{
      width:'25%', 
      flexBasis:'25%',
    },
    labelAndValue:{
      display:'flex',
      flexDirection:'row',
      justifyContent:'space-between',
      flexWrap:'nowrap',
    },
    label:{
      fontSize:14,
      fontFamily:'Roboto',
      color:'grey',
      flexBasis:"33%",
      padding:"11px 5px",
      textAlign:'left',
      wordBreak:'normal',
    },
    value:{
      fontSize:14,
      fontFamily:'Roboto',
      fontWeight:'bold',
      flexBasis:"67%",
      borderBottom: '1px solid #eee',
      textAlign:'left',
      margin:"11px 0",
      display:"flex",
      alignItems:"end",
      wordBreak:'normal',
    },
    amountReceivedContainer:{
      marginRight:5,
      padding:'34px 5px', 
      backgroundColor:'#78ae54',
      display:'flex',
      flexWrap: 'nowrap',
      flexDirection:'column',
      alignItems:'center',
      justifyContent:'space-between',
    },
    amountReceivedFormat:{
      fontFamily:'Roboto', fontWeight:'bold', color:'#ffffff', fontSize:16, wordBreak:'normal',
    },
    billTo: {
      padding: 5,
      lineHeight:1.5,
      display:'flex',
      flexDirection:'row',
      justifyContent: 'space-between',
      marginTop:50,
      textAlign:'left',
      fontSize: 10,
      fontFamily:'Roboto',
      marginBottom:100,
      // pageBreakInside:'avoid',
    },
    billToHeading:{
      fontSize:14,
      fontFamily:'Roboto',
      fontWeight:'bold',
      color:'#777777',
      marginBottom:13,
      textAlign:'left',
    },
    partyName:{
      fontSize: 14,
      fontFamily:'Roboto',
      fontWeight:'bold',
      color:'blue',
      textAlign:'left',
    },
    divider:{
      borderBottom:'1px solid #ededed',
      margin:'10px -30px'
    },
    overPayment:{
      padding:'20px 0 20px 20px',
      borderBottom:'1px solid #ededed',
      textAlign:'left',
      pageBreakInside:'avoid',
    },
    receiptBreakup:{
      marginTop:50,
      marginBottom:30,
      pageBreakInside:'avoid',
      textAlign:'left',
    },
    tableHeader: {
      backgroundColor:'#eff0f1',
      display:'flex',
      flexDirection: 'row',
      borderBottom: 1,
      borderBottomColor: '#aaaaaa',
      marginTop:10,
    },
    th: {
      width: '25%',
      fontSize:12,
      fontWeight:'bold',
      textAlign: 'left',
      borderRight:1,
      borderRightColor: '#aaaaaa',
      padding: '5px',
      flex:1,
    },
    tr: {
      display:'flex',
      flexDirection: 'row',
      borderBottom: 1,
      borderBottomColor: '#aaaaaa',
      padding: '5px',
    },
    td: {
      flex:1,
      textAlign: 'left',
      fontSize: 12,
      padding: '5px 5px',
    },
};