import { getDbController } from "../../db/accountingDb";

const getAutoGeneratedVchNo = async (req, res) => {
    try {
        const {orgId, voucherName, voucherDate} = req.params;
        const dbController = await getDbController(orgId);
        const vchNo = await dbController.voucherType.getLastAutoGeneratedVchNo(voucherName, voucherDate);
        const autoGeneratedVchNo = Number(vchNo) + 1;
        res.json({voucherNumber: autoGeneratedVchNo});
    } catch (error) {
        console.log(error);
        res.status(403).json({error});
    }
};

export default getAutoGeneratedVchNo;
