import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import header from "./createAuthHeader";
import REACT_APP_API_END_POINT from "./apiEndpoint";

export const transactionsApi = createApi({
    reducerPath: "transactionsApi",
    baseQuery: fetchBaseQuery({
        baseUrl: REACT_APP_API_END_POINT,
        prepareHeaders: (headers) => {
            headers.set('Authorization', header['Authorization']);
            return headers;
        },
    }),
    endpoints: (builder) => ({
        getLedgerBalance: builder.query({
            query: (orgId) => `/api/getallbalances/${orgId}`,
            providesTags: ['ClosingBalance'], 
        }),
        getVouchers: builder.query({
            query: (params) => `/api/getvouchers/${params.orgId}/${params.voucher}`,
            providesTags: ['ClosingBalance'],
        }),
        getVoucherData: builder.query({
            query: (params) => `/api/getvoucherdata/${params.orgId}/${params.voucher}/${params.transactionId}`,
            providesTags: ['ClosingBalance'],
        }),
        getCustomerMonthlyIncome: builder.query({
            query: (params) => `/api/getcustomermonthlyincome/${params.orgId}/${params.customerLedgerId}`,
            providesTags: ['ClosingBalance'],
        }),
        getVendorMonthlyExpense: builder.query({
            query: (params) => `/api/getvendormonthlyexpense/${params.orgId}/${params.vendorLedgerId}`,
            providesTags: ['ClosingBalance'],
        }),
        getLedgerTransactions: builder.query({
            query: (params) => `/api/getledgertransactions/${params.orgId}/${params.ledgerId}`,
            providesTags: ['ClosingBalance'],
        }),
        getAutoGeneratedVchNo: builder.query({
            query:(params) => `/api/getautogeneratedvchno/${params.orgId}/${params.voucherName}/${params.voucherDate}`,
            providesTags: ['ClosingBalance']            
        }),
        getUnpaidVouchers: builder.query({
            query: (params) => `/api/getunpaidvouchers/${params.orgId}/${params.primaryVoucherType}`,
            providesTags: ['ClosingBalance']
        }),
        getGroupRunningBalances: builder.query({
            query: (requestObject) => ({
                url:`/api/getrunningbalanceofgroup/${requestObject.params.orgId}/${requestObject.params.groupId}`,
                method:'GET',
            }),
            transformResponse: (response) => response?.[0],
            providesTags: ['ClosingBalance'],
        }),
        getCashFlowMonthlyData: builder.query({
            query:({params}) => `/api/getcashflowmonthlydata/${params.orgId}`,
            providesTags: ['Closingbalance'],
        }),
        getMonthlyIncomeAndExpense: builder.query({
            query:({params}) => `/api/getincomeandexpensemonthlydata/${params.orgId}`,
            providesTags: ['Closingbalance'],
        }),
        getExpenseMonthlyData: builder.query({
            query:({params}) => `/api/getexpensesmonthlydata/${params.orgId}`,
            providesTags: ['Closingbalance'],
        }),
        createVoucher: builder.mutation({
            query: (requestObject) => ({
                url: `/api/createvoucher`,
                method: 'POST',
                body: requestObject,
            }),
            invalidatesTags: ['ClosingBalance'],
        }),
        deleteVoucherEntry: builder.mutation({
            query: (requestObject) => ({
                url: `/api/deletevoucherentry/${requestObject.params.orgId}`,
                method: 'DELETE',
                body: {...requestObject.body},
            }),
            invalidatesTags: ['ClosingBalance'],
        }),
        updateVoucherEntry: builder.mutation({
            query: (requestObject) => ({
                url: `/api/updatevoucherdata/${requestObject.params.orgId}/${requestObject.params.transactionId}/${requestObject.params.otherDetailsId}`,
                method: 'PATCH',
                body: requestObject.body,                
            }),
            invalidatesTags:['ClosingBalance'],
        }),
        updateOffsetTransactions: builder.mutation({
            query: ({params, body}) => ({
                url: `/api/updateoffsettransactions/${params.orgId}/${params.entityId}/${params.receiptTransactionId}`,
                method: 'PATCH',
                body: body,
            }),
            invalidatesTags:['ClosingBalance'],
        }),

    }),
});

export const { 
    useGetLedgerBalanceQuery, useCreateVoucherMutation, useGetVouchersQuery , useGetVoucherDataQuery,
    useDeleteVoucherEntryMutation, useUpdateVoucherEntryMutation, useGetCustomerMonthlyIncomeQuery,
    useGetLedgerTransactionsQuery, useGetAutoGeneratedVchNoQuery, useGetUnpaidVouchersQuery,
    useUpdateOffsetTransactionsMutation, useGetVendorMonthlyExpenseQuery, useGetGroupRunningBalancesQuery,
    useGetCashFlowMonthlyDataQuery, useGetMonthlyIncomeAndExpenseQuery, useGetExpenseMonthlyDataQuery,
} = transactionsApi;
